#!/bin/sh
#
# ushare.sh for rc.d usage (c) 2007 Volker Theile <votdev@gmx.de>.
#

# PROVIDE: ushare
# REQUIRE: DAEMON
# BEFORE: LOGIN
# KEYWORD: shutdown

# Add the following line to /etc/rc.conf to enable `ushare':
#
#ushare_enable="YES"

. "/etc/rc.subr"

name=ushare
rcvar=`set_rcvar`

command="/usr/local/bin/$name"
command_args="--daemon"
required_files="/usr/local/etc/$name.conf"

# read configuration and set defaults
load_rc_config "$name"
: ${ushare_enable="NO"}
: ${ushare_flags=""}
 
run_rc_command "$1"
