/* Automatically generated by configure - do not modify! */
#define VERSION "1.1a"
#define PACKAGE "ushare"
#define PACKAGE_NAME "uShare"
#define SYSCONFDIR "/data/ushare"
#define LOCALEDIR "/data/ushare/locale"
//#define CONFIG_NLS 1
#define BSD 1
